<?php
echo "<font color= black face='Calibri'>";


echo "Hello World, My Name is Emil Kristanti Sitorus Pane";

echo "<br>";
echo "<br>";

echo "<B>";
echo "DATA DIRI";
echo "<br>";
echo "<br>";

echo "<table width='560' border='0'>";
  echo "<tr>";
    echo "<td width='51'>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td width='227'>";
        echo "Nama Lengkap";
        echo "</td>";
    echo "<td width='8'>";
        echo ":";
        echo "</td>";
    echo "<td width='254'>";
        echo "Muhammad alifian .r";
        echo "</td>";
  echo "</tr>";

  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Nama Panggilan";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "EMIL";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
      
    echo "<td>";
        echo "Tempat, Tanggal Lahir";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "MALANG, 23 MARET 1997";
        echo "</td>";
  echo "</tr>";

  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Asal SMP";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "SMPN 5 MALANG";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
      
    echo "<td>";
        echo "Alamat";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Jl. WERKUDARA I NO 52 RT:07 RW : 02 MALANG";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
      
    echo "<td>";
        echo "Tinggi/ Berat";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "170/ 54";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
      
    echo "<td>";
        echo "Cita-cita";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "DOKTER";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Agama";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "KRISTEN PROTESTAN";
        echo "</td>";
  echo "</tr>";

  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Hobi";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "MENYANYI";
        echo "</td>";
  echo "</tr>";
echo "</table>";
?>
